services:
  app:
    build: docker_files
    image: schoolmaster/php:8.3
    volumes:
      - .:/var/www/html
    networks:
      default:
        aliases:
          - ${SERVERNAME_REST}
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      #SERVER_NAME: ${SERVERNAME_REST}
      DOCUMENT_ROOT: public
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "8001:80"

  dbmysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_FORWARD_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql-data:
