name: schoolmaster-backend

services:
  app:
    build: .
    image: schoolmaster/php:8.3
    volumes:
      - ../:/var/www/html
      - ../../schoolmaster-specs:/var/www/schoolmaster-specs:ro
      - ../../schoolmaster-specs:/schoolmaster-specs:ro
    networks:
      default:
        aliases:
          - ${SERVERNAME_REST}
          - mysql
    environment:
      APP_ENV: testing
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: schoolmaster_testing
      DB_USERNAME: schoolmaster
      DB_PASSWORD: secret
      CACHE_STORE: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
      MAIL_MAILER: array
      #SERVER_NAME: ${SERVERNAME_REST}
      DOCUMENT_ROOT: public
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8001:80"

  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_FORWARD_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql-data:
